name: 🐞 バグ報告
description: アプリで見つかった不具合を報告する
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: バグの内容
      description: どんな問題が起きたかを具体的に記述してください。
      placeholder: 例）ログインできない、保存されない、など
  - type: input
    id: steps
    attributes:
      label: 再現手順
      placeholder: 例）1. xxx をクリック → 2. xxx を入力 → 3. xxx を実行
  - type: input
    id: environment
    attributes:
      label: 環境情報
      placeholder: OS、ブラウザ、バージョンなど
